# Generated by Django 5.0.6 on 2024-06-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_by', models.CharField(max_length=255)),
                ('reviwed_on', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
    ]
